[tool.poetry]
name = "curriculumquiz"
version = "0.1.0"
description = ""
authors = ["Merlin Schäfer"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.88.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
